import pandas as pd
import numpy as np


KEYPOINT_LABELS = np.array([['filepath',
                             'pose_type',
                             'x_nose',
                             'x_left_eye',
                             'x_right_eye',
                             'x_left_ear',
                             'x_right_ear',
                             'x_left_shoulder',
                             'x_right_shoulder',
                             'x_left_elbow',
                             'x_right_elbow',
                             'x_left_wrist',
                             'x_right_wrist',
                             'x_left_hip',
                             'x_right_hip',
                             'x_left_knee',
                             'x_right_knee',
                             'x_left_ankle',
                             'x_right_ankle',
                             'y_nose',
                             'y_left_eye',
                             'y_right_eye',
                             'y_left_ear',
                             'y_right_ear',
                             'y_left_shoulder',
                             'y_right_shoulder',
                             'y_left_elbow',
                             'y_right_elbow',
                             'y_left_wrist',
                             'y_right_wrist',
                             'y_left_hip',
                             'y_right_hip',
                             'y_left_knee',
                             'y_right_knee',
                             'y_left_ankle',
                             'y_right_ankle',
                             'pred_nose',
                             'pred_left_eye',
                             'pred_right_eye',
                             'pred_left_ear',
                             'pred_right_ear',
                             'pred_left_shoulder',
                             'pred_right_shoulder',
                             'pred_left_elbow',
                             'pred_right_elbow',
                             'pred_left_wrist',
                             'pred_right_wrist',
                             'pred_left_hip',
                             'pred_right_hip',
                             'pred_left_knee',
                             'pred_right_knee',
                             'pred_left_ankle',
                             'pred_right_ankle', ]])

KEYPOINT_DICT = {
    'nose': 0,
    'left_eye': 1,
    'right_eye': 2,
    'left_ear': 3,
    'right_ear': 4,
    'left_shoulder': 5,
    'right_shoulder': 6,
    'left_elbow': 7,
    'right_elbow': 8,
    'left_wrist': 9,
    'right_wrist': 10,
    'left_hip': 11,
    'right_hip': 12,
    'left_knee': 13,
    'right_knee': 14,
    'left_ankle': 15,
    'right_ankle': 16
}
